version: "3"
services:

  #nginx------------------------------------------------------------------------------------------
  nginx:
    image: "nginx:1.18-perl"
    ports: #映射端口到宿主机
      - "80:80"
      - "444:443"
    expose: #暴露端口到内部网络
      - 9501
    volumes: #挂载路径或文件
     - ${WWW_ROOT}:/var/www/html:ro
     - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d:rw
     - ${CONF_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ${LOG_DIR}/nginx:/usr/share/nginx/logs
    networks:
      web:
        ipv4_address: 172.50.0.10
    restart: always
    extra_hosts:
     - "www.test.work:172.50.0.10"

  #php71------------------------------------------------------------------------------------------
  php71:
    build:
      context: "./build/php71"
      args:
        PHP_VERSION: 7.1
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        APK_PACKAGE: "zlib,linux-headers,libjpeg-turbo-dev,libpng-dev,freetype-dev,libwebp-dev,libxpm-dev,bzip2-dev,libxslt-dev,readline-dev,libedit-dev,libmcrypt-dev"
        PHP_EXTENSIONS: "gd;--with-freetype-dir;--with-jpeg-dir;--with-webp-dir;--with-xpm-dir,pdo_mysql,pcntl,mysqli,bcmath,calendar,opcache,sockets,shmop,sysvmsg,sysvsem,sysvshm,bz2,soap,xsl"
        PHP_PECL: "redis"
    volumes: #挂载路径或文件
      - ${WWW_ROOT}:/var/www/html:rw
      - ${CONF_DIR}/php71/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_DIR}/php71/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}/php71:/var/log/php:rw
    expose: #暴露端口到内部网络
      - 9000
    networks:
      web:
        ipv4_address: 172.50.0.21
    restart: always
    extra_hosts:
      - "www.test.work:172.50.0.10"

  #php74------------------------------------------------------------------------------------------
  php74:
    build:
      context: "./build/php74"
      args:
        PHP_VERSION: 7.4
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        APK_PACKAGE: "zlib,linux-headers,libjpeg-turbo-dev,libpng-dev,freetype-dev,libwebp-dev,libxpm-dev,bzip2-dev,libxslt-dev,readline-dev,libedit-dev,libmcrypt-dev"
        PHP_EXTENSIONS: "gd;--with-freetype;--with-jpeg;--with-webp;--with-xpm,zip,pdo_mysql,pcntl,mysqli,bcmath,calendar,opcache,sockets,shmop,sysvmsg,sysvsem,sysvshm,bz2,soap,xsl"
        PHP_PECL: "redis,mcrypt"
    volumes: #挂载路径或文件
      - ${WWW_ROOT}:/var/www/html:rw
      - ${CONF_DIR}/php74/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_DIR}/php74/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}/php74:/var/log/php:rw
    expose: #暴露端口到内部网络
      - 9000
    networks:
      web:
        ipv4_address: 172.50.0.24
    restart: always
    extra_hosts:
    - "www.test.work:172.50.0.10"

  #php8------------------------------------------------------------------------------------------
  php:
    build:
      context: "./build/php8"
      args:
        PHP_VERSION: 8.0
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_APK: "flibzip-dev,libjpeg-turbo-dev,libpng-dev,freetype-dev,libwebp-dev,libxpm-dev,libxml2-dev,bzip2-dev"
        PHP_EXTENSIONS: "bcmath,gd --with-freetype --with-jpeg --with-webp --with-xpm,sysvshm,zip,pgsql,pdo_mysql,pdo_pgsql,pcntl,mysqli,calendar,opcache,sockets,shmop,sysvmsg,sysvsem,bz2,soap,xsl"
        PHP_PECL: "msgpack,igbinary,redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf"
    volumes: #挂载路径或文件
      - ${WWW_ROOT}:/var/www/html:rw
      - ${CONF_DIR}/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_DIR}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}/php:/var/log/php:rw
    expose: #暴露端口到内部网络
      - 9000
    networks:
      web:
        ipv4_address: 172.50.0.28
#    entrypoint: ["php","/var/www/html/server/workerman.php","start","-d"]
    restart: always
    extra_hosts:
      - "www.test.work:172.50.0.10"

  #redis------------------------------------------------------------------------------------------
  redis:
    image: redis:6.0
    volumes: #挂载路径或文件
      - ${CONF_DIR}/redis/redis.conf:/etc/redis.conf:ro
    expose: #暴露端口到内部网络
      - 6379
    ports:
      - "6379:6379"
    networks:
      web:
        ipv4_address: 172.50.0.30
    entrypoint: ["redis-server", "/etc/redis.conf"]
    restart: always
    extra_hosts:
      - "www.test.work:172.50.0.10"

  #mysql------------------------------------------------------------------------------------------
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes: #挂载路径或文件
      - ${CONF_DIR}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    expose: #暴露端口到内部网络 mysql –u root –p root -D test   mysql –uroot –proot -Dtest     mysql -uroot –proot -Dtest
      - 3306
    ports:
      - "3306:3306"
    networks:
      web:
        ipv4_address: 172.50.0.42
    restart: always
    extra_hosts:
      - "www.test.work:172.50.0.10"

  #postgres------------------------------------------------------------------------------------------
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      ALLOW_IP_RANGE: 0.0.0.0/0
      TZ: Asia/Shanghai
    volumes: #挂载路径或文件
      - ${PGSQL_DATA_DIR}:/var/lib/postgresql/data:rw
    expose: #暴露端口到内部网络
      - 5432
    ports:
      - "5432:5432"
    networks:
      web:
        ipv4_address: 172.50.0.43
    restart: always
    extra_hosts:
      - "www.test.work:172.50.0.10"

#networks------------------------------------------------------------------------------------------
networks:
  web:
    driver: "bridge" # 创建一个docker 的桥接网络
    ipam:
      driver: default
      config:
        -
         subnet: 172.50.0.0/24
